### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by Hube2** [Hube2/contact-form-7-dynamic-select-extension#2]
Add the ability to set default values. See this support request https://wordpress.org/support/topic/manually-set-default-selected

**Comment by v-pvl** [comment]
How can I set the selected value when I am populating the select? I don't want to set a default in admin, my value comes from another page.

**Comment by Hube2** [comment]
Look at the example in the example filter file cf7-dynamic-select-examples.php.

Set a element of the returned array with the index of 'default', you can return either a single string value as the default for a single select field or an array of elements if you want to set more than one default value for multi-select fields
