### ISSUE TITLE
Check to see if Contact Form 7 is activated

### ISSUE THREAD

**Issue by CHEWX** [Hube2/contact-form-7-dynamic-select-extension#8]
Hi,

Your plugin kills the website if your plugin is activated before Contact Form 7.

`
Fatal error: Call to undefined function wpcf7_add_shortcode() in /../../../../wp-content/plugins/contact-form-7-dynamic-select-extension/cf7-dynamic-select.php on line 32`

Thanks,
Tom

**Comment by Hube2** [comment]
will look into it.
